definitions:
  models.DestinationCreate:
    properties:
      distance:
        type: integer
      from:
        type: string
      price:
        type: integer
      to:
        type: string
    type: object
  models.DestinationUpdate:
    properties:
      distance:
        type: integer
      from:
        type: string
      price:
        type: integer
      to:
        type: string
    type: object
  models.ResponseError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  models.SuccessModel:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/destination:
    post:
      consumes:
      - application/json
      description: API for create destination
      parameters:
      - description: destination
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.DestinationCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create destination
      tags:
      - destination
  /v1/destination/{id}:
    put:
      consumes:
      - application/json
      description: API for updating destination
      parameters:
      - description: destination
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.DestinationUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Update destination
      tags:
      - destination
swagger: "2.0"
