CREATE TABLE IF NOT EXISTS bus_seat(
    id SERIAL PRIMARY KEY,
    seat_number INT,
    bus_id INT REFERENCES bus(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);